run:
  timeout: 5m
  tests: true

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
    check-err-return: true
  
  goconst:
    min-len: 2
    min-occurrences: 2
  
  gocritic:
    enabled-tags:
      - performance
      - style
    disabled-checks:
      - dupImport
      - ifElseChain
      - octalLiteral
      - whyNoLint
      - wrapperFunc
  
  gocyclo:
    min-complexity: 15
  
  goimports:
    local-prefixes: dbruntime
  
  revive:
    rules:
      - name: exported
        severity: warning
  
  
  misspell:
    locale: US
  
  nolintlint:
    allow-leading-space: true
    allow-unused: false
    require-explanation: false
    require-specific: false

linters:
  disable-all: true
  enable:
    - errcheck
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - revive
    - gosec
    - govet
    - shadow
    - ineffassign
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - rowserrcheck
    - staticcheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace

issues:
  exclude-dirs:
    - vendor
  exclude-files:
    - ".*\\.pb\\.go$"
    - ".*\\.gen\\.go$"
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gocyclo
        - goconst
    - text: "Error return value of .((os\\.)?std(out|err)\\..*|.*Close|.*Flush|os\\.Remove(All)?|.*printf?|.*print|.*println) is not checked"
      linters:
        - errcheck
    - text: "exported function .* should have comment"
      linters:
        - revive
    - text: "exported type .* should have comment"
      linters:
        - revive
    - text: "exported method .* should have comment"
      linters:
        - revive
  max-issues-per-linter: 0
  max-same-issues: 0
